import numpy as np
a = np.array([1,2,1])
print(a)
b = np.array(range(1,10,1))
print(b)
c = np.arange(1,10,1)
print(c)
d = np.array(range(1,10,1),dtype= 'int8')
print(d.dtype)
e = np.array(range(1,10,1))
print(e.dtype)
f = e.astype(np.int8)
print(f.dtype)
print(f.shape)
print(f.reshape(3,3))
g = np.arange(0,24,1)
print(g.reshape(2,3,4))
print(g.shape[0])
print(g.flatten())
print(g+5)
print(f+5)
h = np.arange(0,24,1).reshape(2,12)
print(h)
print(h.T)
print(h.transpose())
print(h[0,:])
print(h[[0,1],[1,9]])
i = 3 if 3<4 else 5
print(i)

j = np.zeros((10,10),dtype=int)
print(np.count_nonzero(j))

k = np.arange(10)
